[FIX] base/0.0.0: testing modules use uncommon name
Avoid errors in CI while upgrading with test_testing_utilities
installed.

```
  File "/tmp/tmpvf6gl18h/odoo/master/odoo/addons/base/maintenance/migrations/base/saas~16.1.1.3/pre-20-fields.py", line 14, in migrate
    util.remove_field(cr, model, field, skip_inherit="*")
  File "/tmp/tmpvf6gl18h/odoo/master/odoo/addons/base/maintenance/migrations/util/fields.py", line 92, in remove_field
    _validate_model(model)
  File "/tmp/tmpvf6gl18h/odoo/master/odoo/addons/base/maintenance/migrations/util/helpers.py", line 132, in _validate_model
    raise SleepyDeveloperError("`{}` seems to be a table name instead of model name".format(model))
odoo.upgrade.util.exceptions.SleepyDeveloperError: `o2m_readonly_subfield_parent` seems to be a table name instead of model name
```

Part of odoo/upgrade#4167

Signed-off-by: Christophe Simonis <chs@odoo.com>