[FIX] util/models: Fix compute for renamed model
if model got renamed during migration but related field of model
compute didn't update due to that below traceback raised
for fixing it replaced with according this [patch]
(https://github.com/odoo/upgrade-util/blob/4230096526739591d15eb54652dc835ec8b3e3cc/src/util/models.py#L491)

```
'fleet.fleet_vehicle_menu', 521, 'Fleet > Fleet > Fleet', 726):
 Traceback (most recent call last):
   File "/home/odoo/src/odoo/18.0/odoo/tools/safe_eval.py", line 397, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
   File "", line 2, in <module>
   File "/home/odoo/src/odoo/18.0/odoo/api.py", line 596, in __getitem__
    return self.registry[model_name](self, (), ())
   File "/home/odoo/src/odoo/18.0/odoo/modules/registry.py", line 240, in __getitem__
    return self.models[model_name]
 KeyError: 'stock.production.lot'
```

UPG-2588678
OPW-4592615

closes odoo/upgrade-util#225

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>