[FIX] base/0.0.0: fix SleepyDeveloperError test module
Steps To Reproduce :-
- Install 'test_inherit' in v18.3.
- upgrade to v19 fail with this error.

Error :-
```
 File "/tmp/tmpcxl9d0z9/migrations/util/helpers.py", line 146, in
_validate_model
    raise SleepyDeveloperError("`{}` seems to be a table name instead of model
name".format(model))
odoo.upgrade.util.exceptions.SleepyDeveloperError: `test_mother_underscore`
seems to be a table name instead of model name
```

Useful links :-
[1] : https://github.com/odoo/upgrade-util/blob/75328369a1e099b5369bee86cc31543ea2471f01/src/util/modules.py#L204-L266
[2] : https://github.com/odoo/upgrade-util/blame/master/src/util/helpers.py#L144-L147
[3] : https://github.com/odoo/odoo/blob/19.0/odoo/addons/test_inherit/models/mother_inherit_1.py

upg : 4392491
opw : 6146716

closes odoo/upgrade-util#456

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>