[FIX] base: skip recompute records for archived companies
When a company is archived, its related records
should not be recomputed during the upgrade process. This patch ensures
that the `recompute_fields` method skips records belonging
to the archived companies.

**Root cause:**
- `recompute_fields` selects all records from the model, including those
linked to archived companies, which is causing the issue.

**Fix:**
Add a filter in `recompute_fields` to avoid records for the archived companies

**Traceback**
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/service/server.py", line 1369, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/17.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/modules/registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 234, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/17.0/odoo/modules/migration.py", line 221, in migrate_module
    exec_script(self.cr, installed_version, pyfile, pkg.name, stage, stageformat[stage] % version)
  File "/home/odoo/src/odoo/17.0/odoo/modules/migration.py", line 239, in exec_script
    migrate(cr, installed_version)
  File "/tmp/tmpd_b47ofo/migrations/l10n_mx_edi/saas~16.4.0.3/post-migrate.py", line 81, in migrate
    util.recompute_fields(cr, "account.move", ["l10n_mx_edi_cfdi_to_public"], strategy="commit")
  File "/tmp/tmpd_b47ofo/migrations/util/orm.py", line 249, in wrapper
    return f(*args, **kwargs)
  File "/tmp/tmpd_b47ofo/migrations/util/orm.py", line 305, in recompute_fields
    recompute(records)
  File "/tmp/tmpd_b47ofo/migrations/util/orm.py", line 219, in recompute
    (
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 733, in _recompute_all
    self[field.model_name]._recompute_field(field)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6975, in _recompute_field
    field.recompute(records)
  File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1379, in recompute
    apply_except_missing(self.compute_value, recs)
  File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1352, in apply_except_missing
    func(records)
  File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1401, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/17.0/addons/mail/models/mail_thread.py", line 424, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4921, in _compute_field_value
    fields.determine(field.compute, self)
  File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 102, in determine
    return needle(*args)
  File "/home/odoo/src/enterprise/17.0/l10n_mx_edi/models/account_move.py", line 643, in _compute_l10n_mx_edi_cfdi_to_public
    self.env['l10n_mx_edi.document']._add_customer_cfdi_values(
  File "/home/odoo/src/enterprise/17.0/l10n_mx_edi/models/l10n_mx_edi_document.py", line 678, in _add_customer_cfdi_values
    export_fiscal_position = company._l10n_mx_edi_get_foreign_customer_fiscal_position()
  File "/home/odoo/src/enterprise/17.0/l10n_mx_edi/models/res_company.py", line 74, in _l10n_mx_edi_get_foreign_customer_fiscal_position
    fiscal_position = self.env['account.chart.template'].with_company(self).ref('account_fiscal_position_foreign', raise_if_not_found=False)
  File "/home/odoo/src/odoo/17.0/addons/account/models/chart_template.py", line 1082, in ref
    or self.env.ref(f"account.{self.env.company.parent_ids[0].id}_{xmlid}", raise_if_not_found)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6697, in __getitem__
    return self.browse((self._ids[key],))
IndexError: tuple index out of range
```