[FIX] util/report: Make 'name' argument optional
This [commit](https://github.com/odoo/upgrade-util/pull/215)
ensure that if the name argument is not provided, it will
automatically generate a default value for name based on the model and id.

When we call method get_anchor_link_to_record without name,it fails with

```
TypeError: get_anchor_link_to_record() missing 1 required positional argument: 'name'
```

Updated get_anchor_link_to_record to default 'name' to None if not provided.

Also added a check to ensure 'id' is not a tuple before proceeding with its
[use](https://github.com/odoo/upgrade-util/blob/master/src/util/report.py#L328-L330).