[FIX] util/model: Fix column doesn't exist error
oversight of this
https://github.com/odoo/upgrade-util/commit/3fcc23775a0c2fd4a8503cba0e737a64112c57f9
and fixing
https://upgradeci.odoo.com/upgradeci/run/257513
relation_table introduced from odoo 9
https://github.com/odoo/odoo/commit/9979939cd160a234270426f644c3bb2fdda8b543
So, keeping check here
```
Traceback (most recent call last):
  File "/tmp/tmp7nl45ur1/odoo/8.0/openerp/service/server.py", line 941, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/tmp/tmp7nl45ur1/odoo/8.0/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/tmp/tmp7nl45ur1/odoo/8.0/openerp/modules/loading.py", line 297, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/tmp/tmp7nl45ur1/odoo/8.0/openerp/modules/loading.py", line 142, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/tmp/tmp7nl45ur1/odoo/8.0/openerp/modules/migration.py", line 171, in migrate_module
    migrate(self.cr, pkg.installed_version)
  File "/tmp/tmp7nl45ur1/odoo/8.0/openerp/addons/base/maintenance/migrations/base/7.saas~3.1.3/pre-10-change-modules.py", line 76, in migrate
    util.delete_model(cr, 'ir.actions.wizard')
  File "/tmp/tmp7nl45ur1/odoo/8.0/openerp/addons/base/maintenance/migrations/util/models.py", line 205, in remove_model
    [tuple(tables)],
  File "/tmp/tmp7nl45ur1/odoo/8.0/openerp/sql_db.py", line 171, in wrapper
    return f(self, *args, **kwargs)
  File "/tmp/tmp7nl45ur1/odoo/8.0/openerp/sql_db.py", line 247, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "relation_table" does not exist
LINE 4:                      WHERE relation_table IN ('res_groups_wi...
```

closes odoo/upgrade-util#370

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>