[FIX] util/modules: fix correct latest version
during upgrade because of this in older version
latest_version of module assign as modules
because last third frame is for older_version
is below for fixing this manage depth accordingly.

for older version
```
(Pdb) frame.f_back
<frame object at 0x5fbaf1938540>
(Pdb) from inspect import Parameter, getsourcefile, signature
*** ImportError: cannot import name Parameter
(Pdb) from inspect import getsourcefile
(Pdb) getsourcefile(frame.f_back)
'/home/odoo/src/odoo/10.0/odoo/addons/base/maintenance/migrations/util/modules.py'
(Pdb) getsourcefile(frame.f_back.f_back)
'/home/odoo/src/odoo/10.0/odoo/addons/base/maintenance/migrations/base/9.saas~10.1.3/pre-20-crm_claim.py'
(Pdb) getsourcefile(frame.f_back.f_back.f_back)
'/home/odoo/src/odoo/10.0/odoo/modules/migration.py'
```

for above 16.0 version:

```
'/tmp/tmpu1jmod5o/migrations/util/modules.py'
(Pdb) getsourcefile(frame.f_back.f_back)
'/tmp/tmpu1jmod5o/migrations/util/modules.py'
(Pdb) getsourcefile(frame.f_back.f_back.f_back)
'/tmp/tmpu1jmod5o/migrations/base/saas~15.1.1.3/pre-10-modules.py'
```
before fix:
```
test_9_10.0=> select latest_version from ir_module_module where name='project_issue';
 latest_version
----------------
 modules
(1 row)

test_9_10.0=>
```

After fix:

```
test_9_10.0=> select latest_version from ir_module_module where name='project_issue';
 latest_version
----------------
 10.0.1.0
(1 row)
```

closes odoo/upgrade-util#372

Signed-off-by: Jinane Maksoud (maji) <maji@odoo.com>