[FIX] util/report.py: fix report with braces
When we `format` the report if there are braces on the message we may
get errors. Either missing keys or unbalanced braces.
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/12.0/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/12.0/odoo/modules/loading.py", line 539, in load_modules
    model._register_hook()
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/mail/0.0.0/pre-report-migration.py", line 27, in _register_hook
    util.announce_migration_report(self.env.cr)
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/util/report.py", line 80, in announce_migration_report
    announce(cr, release.major_version, message, format="html", header=None, footer=None, **kw)
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/util/report.py", line 178, in announce
    message = ((header or "") + msg + (footer or "")).format(version=version)
KeyError: 'Start Date &lt;01/04/20+Startnotset'
```
Due to `(('ir.filters', 1935, 'Soldes 2019{Start Date <01/04/20+Startnotset}'), False),`

upg-16515
opw-2566809

Part of odoo/upgrade#2535

Signed-off-by: Christophe Simonis <chs@odoo.com>