[FIX] use unicode when converting to html
Fixes this error when upgrading an Odoo 9 database:

UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 22: ordinal not in range(128)

OPW-6638797

@moduon MT-15840

closes odoo/upgrade-util#524

Assisted-by: Goose + GLM 5.3 Flash
Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>