[FIX] util.html_escape
In python2, `html_escape` always returns a byte-string with
non-ascii characters replaced by their html entities.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/10.0/odoo/service/server.py", line 974, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/10.0/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/10.0/odoo/modules/loading.py", line 318, in load_modules
    report=report, models_to_check=models_to_check)
  File "/home/odoo/src/odoo/10.0/odoo/modules/loading.py", line 136, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/10.0/odoo/modules/migration.py", line 169, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/odoo/src/odoo/10.0/odoo/addons/base/maintenance/migrations/base/0.0.0/pre-match-partner_company.py", line 53, in migrate
    for p_id, p_name, c_id, c_name in rows
  File "/home/odoo/src/odoo/10.0/odoo/addons/base/maintenance/migrations/base/0.0.0/pre-match-partner_company.py", line 53, in <genexpr>
    for p_id, p_name, c_id, c_name in rows
  File "/home/odoo/src/odoo/10.0/odoo/addons/base/maintenance/migrations/util/report.py", line 305, in get_anchor_link_to_record
    anchor_tag = '<a target="_blank" href="{}">{}</a>'.format(url, html_escape(name))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 18: ordinal not in range(128)
```

upg-2642498

opw-4642911

closes odoo/upgrade-util#239

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>
Co-authored-by: agu-odoo <sagu@odoo.com>