[FIX] util/records: fix recursion on remove_view
If we have a custom view (view A) with same `key` as the being
removed view (view B) and it was set B inherits A... when we try
to remove the view B with `xml_id` this will happen:
1. Try to remove view B
2. Try to remove view A in this line[^1] (as B and A has same key)
3. Try to remove view B in this line[^2] (as B is child of A)
4. ...

Steps to reproduce:
1. Install `website_sale` in 18.0
2. Create custom view with
   key=`website_sale.dynamic_filter_template_product_product_borderless_2`
3. Set that view as inherit_id of standard view
   `website_sale.dynamic_filter_template_product_product_borderless_2`
4. Upgrade to 19.0

we will get:

```
 File "/tmp/tmpe3zlvt56/migrations/util/records.py", line 110, in remove_view
    remove_view(cr, view_id=v_id, silent=silent, key=xml_id)
  File "/tmp/tmpe3zlvt56/migrations/util/records.py", line 120, in remove_view
    _remove_redundant_tcalls(cr, key)
  File "/tmp/tmpe3zlvt56/migrations/util/records.py", line 1933, in _remove_redundant_tcalls
    get_value_or_en_translation(cr, "ir_ui_view", "arch_db")
  File "/tmp/tmpe3zlvt56/migrations/util/pg.py", line 500, in get_value_or_en_translation
    return format_query(cr, fmt, column)
  File "/tmp/tmpe3zlvt56/migrations/util/pg.py", line 221, in format_query
    return SQLStr(sql.SQL(query).format(*args, **kwargs).as_string(cr._cnx))
  File "/home/odoo/.odoo-venvs/17.0/lib/python3.10/site-packages/psycopg2/sql.py", line 122, in as_string
    rv.append(i.as_string(context))
  File "/home/odoo/.odoo-venvs/17.0/lib/python3.10/site-packages/psycopg2/sql.py", line 350, in as_string
    return '.'.join(ext.quote_ident(s, context) for s in self._wrapped)
  File "/home/odoo/.odoo-venvs/17.0/lib/python3.10/site-packages/psycopg2/sql.py", line 350, in <genexpr>
    return '.'.join(ext.quote_ident(s, context) for s in self._wrapped)
RecursionError: maximum recursion depth exceeded
```

For fixing the issue, I have moved the part which removes the views with
same key to the end. So view A will be deleted after view B.

Example: UPG-3567940
tbg-2356

```SQL
> SELECT id, name, inherit_id, key FROM ir_ui_view WHERE id IN (7120, 7127, 7831, 8386) order by key
+------+------------------------+------------+-------------------------------------------------------------------+
| id   | name                   | inherit_id | key                                                               |
|------+------------------------+------------+-------------------------------------------------------------------|
| 7120 | Classic Card           | 8386       | website_sale.dynamic_filter_template_product_product_add_to_cart  |
| 8386 | Custom Sales View      | <null>     | website_sale.dynamic_filter_template_product_product_add_to_cart  |
| 7127 | Borderless Product n°2 | 7831       | website_sale.dynamic_filter_template_product_product_borderless_2 |
| 7831 | custom view            | <null>     | website_sale.dynamic_filter_template_product_product_borderless_2 |
+------+------------------------+------------+-------------------------------------------------------------------+

> SELECT id, res_id, model, module FROM ir_model_data WHERE res_id IN (7831, 8386, 7120, 7127) AND model = 'ir.ui.view';
+--------+--------+------------+--------------+
| id     | res_id | model      | module       |
|--------+--------+------------+--------------|
| 122569 | 7120   | ir.ui.view | website_sale |
| 122576 | 7127   | ir.ui.view | website_sale |
+--------+--------+------------+--------------+

```

[^1]: https://github.com/odoo/upgrade-util/blob/27aea035975c053b537eab1b4832e7b8092506a7/src/util/records.py#L110
[^2]: https://github.com/odoo/upgrade-util/blob/27aea035975c053b537eab1b4832e7b8092506a7/src/util/records.py#L144