[FIX] util.remove_field: fix always adapt domains
When removing a field we need to **always** adapt the domain.

Example situation before migration:
```
17512_afu=> select domain_force from ir_rule where id=179
+-----------------------------------------------------------------------------------+
| domain_force                                                                      |
|-----------------------------------------------------------------------------------|
| ['|',                                                                             |
|             ('location_id.operating_unit_id', 'in', user.operating_unit_ids.ids), |
|             ('location_id.operating_unit_id', '=', False)]                        |
|                                                                                   |
+-----------------------------------------------------------------------------------+
```
Leads to this after migration:
```
17512_afu_13.0=> select domain_force from ir_rule where id=179
+--------------------------------------------------------------------------------------------------------------------+
| domain_force                                                                                                       |
|--------------------------------------------------------------------------------------------------------------------|
| ['|', ('ignored.operating_unit_id', 'in', user.operating_unit_ids.ids), ('ignored.operating_unit_id', '=', False)] |
+--------------------------------------------------------------------------------------------------------------------+
```

With this fix:
```
17512_afu_13.0=> select domain_force from ir_rule where id=179
+---------------------------------+
| domain_force                    |
|---------------------------------|
| ['|', (0, '=', 1), (0, '=', 1)] |
+---------------------------------+
```

Original traceback:
```
 Traceback (most recent call last):
   File "/tmp/tmpf2adcl0f/migrations/base/tests/test_mock_crawl.py", line 175, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpf2adcl0f/migrations/base/tests/test_mock_crawl.py", line 266, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmpf2adcl0f/migrations/base/tests/test_mock_crawl.py", line 381, in mock_view_tree
    self.mock_web_search_read(model, view, [domain], fields_list)
   File "/tmp/tmpf2adcl0f/migrations/base/tests/test_mock_crawl.py", line 415, in mock_web_search_read
    data = model.search_read(domain=domain, fields=fields_list, limit=80)
   File "/home/odoo/src/odoo/13.0/odoo/models.py", line 4934, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
   File "/home/odoo/src/odoo/13.0/odoo/models.py", line 1648, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
   File "/home/odoo/src/odoo/13.0/odoo/models.py", line 4480, in _search
    self._apply_ir_rules(query, 'read')
   File "/home/odoo/src/odoo/13.0/odoo/models.py", line 4260, in _apply_ir_rules
    where_clause, where_params, tables = Rule.domain_get(self._name, mode)
   File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_rule.py", line 188, in domain_get
    query = self.env[model_name].sudo()._where_calc(dom, active_test=False)
   File "/home/odoo/src/odoo/13.0/odoo/models.py", line 4199, in _where_calc
    e = expression.expression(domain, self)
   File "/home/odoo/src/odoo/13.0/odoo/osv/expression.py", line 681, in __init__
    self.parse()
   File "/home/odoo/src/odoo/13.0/odoo/osv/expression.py", line 862, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
 ValueError: Invalid field 'ignored.operating_unit_id' in leaf "<osv.ExtendedLeaf: ('ignored.operating_unit_id', 'in', [1, 2, 3, 4, 8]) on stock_inventory (ctx: )>"
```

upg-17512

Part of odoo/upgrade#2598

Signed-off-by: Christophe Simonis <chs@odoo.com>