[FIX] records
Correct hardcoded tables, they should be models.

```
Traceback (most recent call last):
  File "/upgrade-util/src/base/tests/test_util.py", line 573, in test_remove_field
    util.remove_field(self.cr, "res.currency.rate", "company_id")
  File "/upgrade-util/src/util/fields.py", line 247, in remove_field
    _remove_import_export_paths(cr, model, fieldname)
  File "/upgrade-util/src/util/records.py", line 615, in _remove_import_export_paths
    remove_records(cr, impex_model, to_rem)
  File "/upgrade-util/src/util/records.py", line 431, in remove_records
    _validate_model(model)
  File "/upgrade-util/src/util/helpers.py", line 155, in _validate_model
    raise SleepyDeveloperError("`{}` seems to be a table name instead of model name".format(model))
odoo.upgrade.util.exceptions.SleepyDeveloperError: `ir_exports_line` seems to be a table name instead of model name
```

Part-of: odoo/upgrade-util#475
Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>