[FIX] util/testing: avoid registry error in UpgradeCase
When we upgrade with a custom module, more precisely a module that is
not in the addons path, we leave them in a transient `to upgrade` state.
This is necessary to ensure we trigger the upgrade of the module once
the DB is restored. The issue is that this also leads to all
`UpgradeCase` tests failing with:
```
Traceback (most recent call last):
  File "/home/odoo/src/upgrade/migrations/testing.py", line 417, in setUp
    self.env = api.Environment(self.cr, SUPERUSER_ID, {})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-19.4/odoo/orm/environments.py", line 75, in __new__
    transaction._check_signaling(cr)
  File "/home/odoo/src/odoo/saas-19.4/odoo/orm/environments.py", line 774, in _check_signaling
    self.registry = registry = Registry.new(registry.db_name)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-19.4/odoo/tests/common.py", line 665, in forbidden
    raise RuntimeError("cannot call Registry.new during testing")
RuntimeError: cannot call Registry.new during testing
```

The root issue is a [change] in saas~19.4 in the way the registry
coordinates changes. It uses the table [orm_signaling_registry] (or
rather the max ID of any row in the table) as the way to synchronize
registry setups. A new registry is created as soon as a desync in the
sequence (loaded vs orm_signaling_registry) is [detected]. The
[presence] of modules in `to upgrade` state triggers a sequence
[increase] during loading, that leads to a new registry. The error is
then in the [blockage] of a new registry setup during tests.

In this patch we propose to mock the sequence fetching mechanisms as done
for [`TransactionCase`]

[change]: https://github.com/odoo/odoo/commit/9fca3bea4427f566ff0a33fdb6f20ab73f60e44f
[orm_signaling_registry]: https://github.com/odoo/odoo/blob/6c350f74b81d68fd86a76f4fb237c60869cf5c86/odoo/orm/registry.py#L1076-L1082
[detected]: https://github.com/odoo/odoo/blob/6c350f74b81d68fd86a76f4fb237c60869cf5c86/odoo/orm/environments.py#L772-L774
[presence]: https://github.com/odoo/odoo/blob/6c350f74b81d68fd86a76f4fb237c60869cf5c86/odoo/orm/registry.py#L190-L201
[increase]: https://github.com/odoo/odoo/blob/6c350f74b81d68fd86a76f4fb237c60869cf5c86/odoo/modules/loading.py#L499-L500
[blockage]: https://github.com/odoo/odoo/blob/6c350f74b81d68fd86a76f4fb237c60869cf5c86/odoo/tests/common.py#L662-L666
[`TransactionCase`]: https://github.com/odoo/odoo/blob/6c350f74b81d68fd86a76f4fb237c60869cf5c86/odoo/tests/common.py#L1352-L1366