[IMP] util/pg: skip `None` counts when summing
[cr.rowcount](https://www.psycopg.org/docs/cursor.html#cursor.rowcount)
may start (at some non-disclosed point) to return `None` instead of `-1`.

Which would cause the following error:

```python
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```